name: Run autotests

on: [push]

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Set up dependencies
        run: pip install -r requirements.txt
      - name: chrome version
        run: google-chrome --version
      - name: Run tests
        run: pytest -v
      
